/// <reference types="Cypress" />
const faker = require('faker')
let name = faker.name.firstName()
let lstname = faker.name.lastName()
let zipcode = faker.address.zipCode()

Cypress.Commands.add('sauce_labs_bp_checkout', () => {
    //Iten
    cy.get('[data-test=add-to-cart-sauce-labs-backpack]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Backpack')
    cy.get('.inventory_item_desc').and('contain', 'carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.')
    cy.get('.inventory_item_price').and('contain', '$').and('contain','29.99')
    
    //Checkout: your information
    cy.get('[data-test=checkout]').click()
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Your Information')
    cy.get('[data-test=firstName]').invoke('attr', 'placeholder').should('contain', 'First Name')
    cy.get('[data-test=firstName]').type(name)
    cy.get('[data-test=lastName]').invoke('attr', 'placeholder').should('contain', 'Last Name')
    cy.get('[data-test=lastName]').type(lstname)
    cy.get('[data-test=postalCode]').invoke('attr', 'placeholder').should('contain', 'Zip/Postal Code')
    cy.get('[data-test=postalCode]').type(zipcode)
    cy.get('[data-test=continue]').click()
    
    //Checkout Overview
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Overview')
    cy.get('.cart_desc_label').should('be.visible').and('contain', 'DESCRIPTION')
    cy.get('.cart_item > div').should(($divs) => {
        expect($divs, '1 Item').to.have.length(2)
        expect($divs.eq(0), 'QTY').to.contain('1')
        expect($divs.eq(1), 'First  item')
                .to.contain('Sauce Labs Backpack')
                .to.contain('$')
                .to.contain('29.99')
    })
    cy.get('.summary_info > div').should(($divs => {
        expect($divs.eq(0), 'Payment').to.contain('Payment Information:')
        expect($divs.eq(1), 'Credit Card').to.contain('SauceCard #31337')
        expect($divs.eq(2), 'Shipping').to.contain('Shipping Information:')
        expect($divs.eq(3), 'Shipping Method').to.contain('FREE PONY EXPRESS DELIVERY!')
        expect($divs.eq(4), 'Item total').to.contain('Item total: $')
        expect($divs.eq(5), 'Tax')
                .to.contain('Tax: $')
                .to.contain('2.40')
        expect($divs.eq(6), 'Total')
                .to.contain('Total: $')
                .to.contain('32.39')
    }))
    cy.get('[data-test=cancel]').should('be.visible').and('contain', 'Cancel')
    cy.get('[data-test=finish]').should('be.visible').and('contain', 'Finish')
    cy.get('[data-test=finish]').click()
    
    //Checkout Complete
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Complete!')
    cy.get('.complete-header').should('be.visible').and('contain', 'THANK YOU FOR YOUR ORDER')
    cy.get('.complete-text').should('be.visible').and('contain', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
    cy.get('.pony_express').should('have.attr', 'src', '/static/media/pony-express.46394a5d.png')
    cy.get('[data-test=back-to-products]').should('be.visible').and('contain', 'Back Home')
    cy.get('[data-test=back-to-products]').click()
})

//sauce_labs_blight
Cypress.Commands.add('sauce_labs_blight_checkout', () => {
    //Item
    cy.get('[data-test=add-to-cart-sauce-labs-bike-light]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Bike Light')
    cy.get('.inventory_item_desc').and('contain', "A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','9.99')
    
    //Checkout: your information
    cy.get('[data-test=checkout]').click()
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Your Information')
    cy.get('[data-test=firstName]').invoke('attr', 'placeholder').should('contain', 'First Name')
    cy.get('[data-test=firstName]').type(name)
    cy.get('[data-test=lastName]').invoke('attr', 'placeholder').should('contain', 'Last Name')
    cy.get('[data-test=lastName]').type(lstname)
    cy.get('[data-test=postalCode]').invoke('attr', 'placeholder').should('contain', 'Zip/Postal Code')
    cy.get('[data-test=postalCode]').type(zipcode)
    cy.get('[data-test=continue]').click()
    
    //Checkout Overview
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Overview')
    cy.get('.cart_desc_label').should('be.visible').and('contain', 'DESCRIPTION')
    cy.get('.cart_item > div').should(($divs) => {
        expect($divs, '1 Item').to.have.length(2)
        expect($divs.eq(0), 'QTY').to.contain('1')
        expect($divs.eq(1), 'First  item')
                .to.contain('Sauce Labs Bike Light')
                .to.contain('$')
                .to.contain('9.99')
    })
    cy.get('.summary_info > div').should(($divs => {
        expect($divs.eq(0), 'Payment').to.contain('Payment Information:')
        expect($divs.eq(1), 'Credit Card').to.contain('SauceCard #31337')
        expect($divs.eq(2), 'Shipping').to.contain('Shipping Information:')
        expect($divs.eq(3), 'Shipping Method').to.contain('FREE PONY EXPRESS DELIVERY!')
        expect($divs.eq(4), 'Item total').to.contain('Item total: $')
        expect($divs.eq(5), 'Tax')
                .to.contain('Tax: $')
                .to.contain('0.80')
        expect($divs.eq(6), 'Total')
                .to.contain('Total: $')
                .to.contain('10.79')
    }))
    cy.get('[data-test=cancel]').should('be.visible').and('contain', 'Cancel')
    cy.get('[data-test=finish]').should('be.visible').and('contain', 'Finish')
    cy.get('[data-test=finish]').click()
    
    //Checkout Complete
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Complete!')
    cy.get('.complete-header').should('be.visible').and('contain', 'THANK YOU FOR YOUR ORDER')
    cy.get('.complete-text').should('be.visible').and('contain', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
    cy.get('.pony_express').should('have.attr', 'src', '/static/media/pony-express.46394a5d.png')
    cy.get('[data-test=back-to-products]').should('be.visible').and('contain', 'Back Home')
    cy.get('[data-test=back-to-products]').click()
})

//sauce_labs_bshirt
Cypress.Commands.add('sauce_labs_bshirt_checkout', () => {
    //item
    cy.get('[data-test=add-to-cart-sauce-labs-bolt-t-shirt]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Bolt T-Shirt')
    cy.get('.inventory_item_desc').and('contain', "Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','15.99')
    
    //Checkout: your information
    cy.get('[data-test=checkout]').click()
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Your Information')
    cy.get('[data-test=firstName]').invoke('attr', 'placeholder').should('contain', 'First Name')
    cy.get('[data-test=firstName]').type(name)
    cy.get('[data-test=lastName]').invoke('attr', 'placeholder').should('contain', 'Last Name')
    cy.get('[data-test=lastName]').type(lstname)
    cy.get('[data-test=postalCode]').invoke('attr', 'placeholder').should('contain', 'Zip/Postal Code')
    cy.get('[data-test=postalCode]').type(zipcode)
    cy.get('[data-test=continue]').click()
    
    //Checkout Overview
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Overview')
    cy.get('.cart_desc_label').should('be.visible').and('contain', 'DESCRIPTION')
    cy.get('.cart_item > div').should(($divs) => {
        expect($divs, '1 Item').to.have.length(2)
        expect($divs.eq(0), 'QTY').to.contain('1')
        expect($divs.eq(1), 'First  item')
                .to.contain('Sauce Labs Bolt T-Shirt')
                .to.contain('$')
                .to.contain('15.99')
    })
    cy.get('.summary_info > div').should(($divs => {
        expect($divs.eq(0), 'Payment').to.contain('Payment Information:')
        expect($divs.eq(1), 'Credit Card').to.contain('SauceCard #31337')
        expect($divs.eq(2), 'Shipping').to.contain('Shipping Information:')
        expect($divs.eq(3), 'Shipping Method').to.contain('FREE PONY EXPRESS DELIVERY!')
        expect($divs.eq(4), 'Item total').to.contain('Item total: $')
        expect($divs.eq(5), 'Tax')
                .to.contain('Tax: $')
                .to.contain('1.28')
        expect($divs.eq(6), 'Total')
                .to.contain('Total: $')
                .to.contain('17.27')
    }))
    cy.get('[data-test=cancel]').should('be.visible').and('contain', 'Cancel')
    cy.get('[data-test=finish]').should('be.visible').and('contain', 'Finish')
    cy.get('[data-test=finish]').click()
    
    //Checkout Complete
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Complete!')
    cy.get('.complete-header').should('be.visible').and('contain', 'THANK YOU FOR YOUR ORDER')
    cy.get('.complete-text').should('be.visible').and('contain', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
    cy.get('.pony_express').should('have.attr', 'src', '/static/media/pony-express.46394a5d.png')
    cy.get('[data-test=back-to-products]').should('be.visible').and('contain', 'Back Home')
    cy.get('[data-test=back-to-products]').click()
})

//sauce_labs_fjacket
Cypress.Commands.add('sauce_labs_fjacket_checkout', () => {
    //item
    cy.get('[data-test=add-to-cart-sauce-labs-fleece-jacket]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Fleece Jacket')
    cy.get('.inventory_item_desc').and('contain', "It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','49.99')

    //Checkout: your information
    cy.get('[data-test=checkout]').click()
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Your Information')
    cy.get('[data-test=firstName]').invoke('attr', 'placeholder').should('contain', 'First Name')
    cy.get('[data-test=firstName]').type(name)
    cy.get('[data-test=lastName]').invoke('attr', 'placeholder').should('contain', 'Last Name')
    cy.get('[data-test=lastName]').type(lstname)
    cy.get('[data-test=postalCode]').invoke('attr', 'placeholder').should('contain', 'Zip/Postal Code')
    cy.get('[data-test=postalCode]').type(zipcode)
    cy.get('[data-test=continue]').click()
    
    //Checkout Overview
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Overview')
    cy.get('.cart_desc_label').should('be.visible').and('contain', 'DESCRIPTION')
    cy.get('.cart_item > div').should(($divs) => {
        expect($divs, '1 Item').to.have.length(2)
        expect($divs.eq(0), 'QTY').to.contain('1')
        expect($divs.eq(1), 'First  item')
                .to.contain('Sauce Labs Fleece Jacket')
                .to.contain('$')
                .to.contain('49.99')
    })
    cy.get('.summary_info > div').should(($divs => {
        expect($divs.eq(0), 'Payment').to.contain('Payment Information:')
        expect($divs.eq(1), 'Credit Card').to.contain('SauceCard #31337')
        expect($divs.eq(2), 'Shipping').to.contain('Shipping Information:')
        expect($divs.eq(3), 'Shipping Method').to.contain('FREE PONY EXPRESS DELIVERY!')
        expect($divs.eq(4), 'Item total').to.contain('Item total: $')
        expect($divs.eq(5), 'Tax')
                .to.contain('Tax: $')
                .to.contain('4.00')
        expect($divs.eq(6), 'Total')
                .to.contain('Total: $')
                .to.contain('53.99')
    }))
    cy.get('[data-test=cancel]').should('be.visible').and('contain', 'Cancel')
    cy.get('[data-test=finish]').should('be.visible').and('contain', 'Finish')
    cy.get('[data-test=finish]').click()
    
    //Checkout Complete
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Complete!')
    cy.get('.complete-header').should('be.visible').and('contain', 'THANK YOU FOR YOUR ORDER')
    cy.get('.complete-text').should('be.visible').and('contain', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
    cy.get('.pony_express').should('have.attr', 'src', '/static/media/pony-express.46394a5d.png')
    cy.get('[data-test=back-to-products]').should('be.visible').and('contain', 'Back Home')
    cy.get('[data-test=back-to-products]').click()
})

//sauce_labs_onesie
Cypress.Commands.add('sauce_labs_onesie_checkout', () => {
    //item
    cy.get('[data-test=add-to-cart-sauce-labs-onesie]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Onesie')
    cy.get('.inventory_item_desc').and('contain', "Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','7.99')
    
     //Checkout: your information
     cy.get('[data-test=checkout]').click()
     cy.get('.title').should('be.visible').and('contain', 'Checkout: Your Information')
     cy.get('[data-test=firstName]').invoke('attr', 'placeholder').should('contain', 'First Name')
     cy.get('[data-test=firstName]').type(name)
     cy.get('[data-test=lastName]').invoke('attr', 'placeholder').should('contain', 'Last Name')
     cy.get('[data-test=lastName]').type(lstname)
     cy.get('[data-test=postalCode]').invoke('attr', 'placeholder').should('contain', 'Zip/Postal Code')
     cy.get('[data-test=postalCode]').type(zipcode)
     cy.get('[data-test=continue]').click()
     
     //Checkout Overview
     cy.get('.title').should('be.visible').and('contain', 'Checkout: Overview')
     cy.get('.cart_desc_label').should('be.visible').and('contain', 'DESCRIPTION')
     cy.get('.cart_item > div').should(($divs) => {
         expect($divs, '1 Item').to.have.length(2)
         expect($divs.eq(0), 'QTY').to.contain('1')
         expect($divs.eq(1), 'First  item')
                 .to.contain('Sauce Labs Onesie')
                 .to.contain('$')
                 .to.contain('7.99')
     })
     cy.get('.summary_info > div').should(($divs => {
         expect($divs.eq(0), 'Payment').to.contain('Payment Information:')
         expect($divs.eq(1), 'Credit Card').to.contain('SauceCard #31337')
         expect($divs.eq(2), 'Shipping').to.contain('Shipping Information:')
         expect($divs.eq(3), 'Shipping Method').to.contain('FREE PONY EXPRESS DELIVERY!')
         expect($divs.eq(4), 'Item total').to.contain('Item total: $')
         expect($divs.eq(5), 'Tax')
                 .to.contain('Tax: $')
                 .to.contain('0.64')
         expect($divs.eq(6), 'Total')
                 .to.contain('Total: $')
                 .to.contain('8.63')
     }))
     cy.get('[data-test=cancel]').should('be.visible').and('contain', 'Cancel')
     cy.get('[data-test=finish]').should('be.visible').and('contain', 'Finish')
     cy.get('[data-test=finish]').click()
     
     //Checkout Complete
     cy.get('.title').should('be.visible').and('contain', 'Checkout: Complete!')
     cy.get('.complete-header').should('be.visible').and('contain', 'THANK YOU FOR YOUR ORDER')
     cy.get('.complete-text').should('be.visible').and('contain', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
     cy.get('.pony_express').should('have.attr', 'src', '/static/media/pony-express.46394a5d.png')
     cy.get('[data-test=back-to-products]').should('be.visible').and('contain', 'Back Home')
     cy.get('[data-test=back-to-products]').click()
})

//sauce_labs_allthings
Cypress.Commands.add('sauce_labs_allthings_checkout', () => {
    //item
    cy.get('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Test.allTheThings() T-Shirt (Red)')
    cy.get('.inventory_item_desc').and('contain', "This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','15.99')

    //Checkout: your information
    cy.get('[data-test=checkout]').click()
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Your Information')
    cy.get('[data-test=firstName]').invoke('attr', 'placeholder').should('contain', 'First Name')
    cy.get('[data-test=firstName]').type(name)
    cy.get('[data-test=lastName]').invoke('attr', 'placeholder').should('contain', 'Last Name')
    cy.get('[data-test=lastName]').type(lstname)
    cy.get('[data-test=postalCode]').invoke('attr', 'placeholder').should('contain', 'Zip/Postal Code')
    cy.get('[data-test=postalCode]').type(zipcode)
    cy.get('[data-test=continue]').click()
    
    //Checkout Overview
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Overview')
    cy.get('.cart_desc_label').should('be.visible').and('contain', 'DESCRIPTION')
    cy.get('.cart_item > div').should(($divs) => {
        expect($divs, '1 Item').to.have.length(2)
        expect($divs.eq(0), 'QTY').to.contain('1')
        expect($divs.eq(1), 'First  item')
                .to.contain('Test.allTheThings() T-Shirt (Red)')
                .to.contain('$')
                .to.contain('15.99')
    })
    cy.get('.summary_info > div').should(($divs => {
        expect($divs.eq(0), 'Payment').to.contain('Payment Information:')
        expect($divs.eq(1), 'Credit Card').to.contain('SauceCard #31337')
        expect($divs.eq(2), 'Shipping').to.contain('Shipping Information:')
        expect($divs.eq(3), 'Shipping Method').to.contain('FREE PONY EXPRESS DELIVERY!')
        expect($divs.eq(4), 'Item total').to.contain('Item total: $')
        expect($divs.eq(5), 'Tax')
                .to.contain('Tax: $')
                .to.contain('1.28')
        expect($divs.eq(6), 'Total')
                .to.contain('Total: $')
                .to.contain('17.27')
    }))
    cy.get('[data-test=cancel]').should('be.visible').and('contain', 'Cancel')
    cy.get('[data-test=finish]').should('be.visible').and('contain', 'Finish')
    cy.get('[data-test=finish]').click()
    
    //Checkout Complete
    cy.get('.title').should('be.visible').and('contain', 'Checkout: Complete!')
    cy.get('.complete-header').should('be.visible').and('contain', 'THANK YOU FOR YOUR ORDER')
    cy.get('.complete-text').should('be.visible').and('contain', 'Your order has been dispatched, and will arrive just as fast as the pony can get there!')
    cy.get('.pony_express').should('have.attr', 'src', '/static/media/pony-express.46394a5d.png')
    cy.get('[data-test=back-to-products]').should('be.visible').and('contain', 'Back Home')
    cy.get('[data-test=back-to-products]').click()
})
//--------------------------------------------------------------------------------------------------------------------------------
