/// <reference types="Cypress" />
//Standard User ------------------------------------------------------------------------------------------------------------------
Cypress.Commands.add('sauce_labs_bp_remove', () => {
    cy.get('[data-test=add-to-cart-sauce-labs-backpack]').click()
    //verifica se o carrinho está presente e tem o badge com a quantidade do item.
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    //Verifica se o carrinho ainda está presente e tem o badge com a quantidade do item
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Backpack')
    cy.get('.inventory_item_desc').and('contain', 'carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.')
    cy.get('.inventory_item_price').and('contain', '$').and('contain','29.99')
    cy.get('[data-test=remove-sauce-labs-backpack]').click()
    cy.get('[data-test=continue-shopping]').click()
    cy.get('.shopping_cart_badge').should('not.exist')
})

Cypress.Commands.add('sauce_labs_blight_remove', () => {
    cy.get('[data-test=add-to-cart-sauce-labs-bike-light]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Bike Light')
    cy.get('.inventory_item_desc').and('contain', "A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','9.99')
    cy.get('[data-test=remove-sauce-labs-bike-light]').click()
    cy.get('[data-test=continue-shopping]').click()
    cy.get('.shopping_cart_badge').should('not.exist')
})

Cypress.Commands.add('sauce_labs_bshirt_remove', () => {
    cy.get('[data-test=add-to-cart-sauce-labs-bolt-t-shirt]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Bolt T-Shirt')
    cy.get('.inventory_item_desc').and('contain', "Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','15.99')
    cy.get('[data-test=remove-sauce-labs-bolt-t-shirt]').click()
    cy.get('[data-test=continue-shopping]').click()
    cy.get('.shopping_cart_badge').should('not.exist')
})

Cypress.Commands.add('sauce_labs_fjacket_remove', () => {
    cy.get('[data-test=add-to-cart-sauce-labs-fleece-jacket]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Fleece Jacket')
    cy.get('.inventory_item_desc').and('contain', "It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','49.99')
    cy.get('[data-test=remove-sauce-labs-fleece-jacket]').click()
    cy.get('[data-test=continue-shopping]').click()
    cy.get('.shopping_cart_badge').should('not.exist')
})

Cypress.Commands.add('sauce_labs_onesie_remove', () => {
    cy.get('[data-test=add-to-cart-sauce-labs-onesie]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Sauce Labs Onesie')
    cy.get('.inventory_item_desc').and('contain', "Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','7.99')
    cy.get('[data-test=remove-sauce-labs-onesie]').click()
    cy.get('[data-test=continue-shopping]').click()
    cy.get('.shopping_cart_badge').should('not.exist')
})

Cypress.Commands.add('sauce_labs_allthings_remove', () => {
    cy.get('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.shopping_cart_link').click()
    cy.get('.shopping_cart_link').should('be.visible')
    cy.get('.shopping_cart_badge').should('be.visible').and('contain', '1')
    cy.get('.title').should('be.visible').and('contain', 'Your Cart')
    cy.get('.cart_quantity_label').should('be.visible')
    cy.get('.cart_quantity').should('be.visible').and('contain', '1')
    cy.get('.inventory_item_name').and('contain', 'Test.allTheThings() T-Shirt (Red)')
    cy.get('.inventory_item_desc').and('contain', "This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.")
    cy.get('.inventory_item_price').and('contain', '$').and('contain','15.99')
    cy.get('[data-test="remove-test.allthethings()-t-shirt-(red)"]').click()
    cy.get('[data-test=continue-shopping]').click()
    cy.get('.shopping_cart_badge').should('not.exist')
})
//--------------------------------------------------------------------------------------------------------------------------------
